version: '3'
services:
  db_dev:
    image: postgres
    volumes:
      - ./tmp/db_dev:/var/lib/postgresql/data
  development:
    restart: always
    build: .
    command: bash -c "dotenv bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/ze_challenge
    depends_on:
      - db_dev
